
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'demodbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'demodbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  demodbt:
    # Config indicated by + and applies to all files under models/example/
    # materialized: [ table, view, incremental, ephemeral ]
    l1_bronze:
      +materialized: view
      +schema: l1_bronze
    l2_silver:
      +materialized: view
      +schema: l2_silver
    l3_golden:
      +materialized: view
      +schema: l3_golden

seeds:
  demodbt:
    +schema: seeds